// Generated by gencpp from file tugas_pkg/magnitude.msg
// DO NOT EDIT!


#ifndef TUGAS_PKG_MESSAGE_MAGNITUDE_H
#define TUGAS_PKG_MESSAGE_MAGNITUDE_H

#include <ros/service_traits.h>


#include <tugas_pkg/magnitudeRequest.h>
#include <tugas_pkg/magnitudeResponse.h>


namespace tugas_pkg
{

struct magnitude
{

typedef magnitudeRequest Request;
typedef magnitudeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct magnitude
} // namespace tugas_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tugas_pkg::magnitude > {
  static const char* value()
  {
    return "55d1a215f43fd1f64eb105a505b172c4";
  }

  static const char* value(const ::tugas_pkg::magnitude&) { return value(); }
};

template<>
struct DataType< ::tugas_pkg::magnitude > {
  static const char* value()
  {
    return "tugas_pkg/magnitude";
  }

  static const char* value(const ::tugas_pkg::magnitude&) { return value(); }
};


// service_traits::MD5Sum< ::tugas_pkg::magnitudeRequest> should match
// service_traits::MD5Sum< ::tugas_pkg::magnitude >
template<>
struct MD5Sum< ::tugas_pkg::magnitudeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tugas_pkg::magnitude >::value();
  }
  static const char* value(const ::tugas_pkg::magnitudeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tugas_pkg::magnitudeRequest> should match
// service_traits::DataType< ::tugas_pkg::magnitude >
template<>
struct DataType< ::tugas_pkg::magnitudeRequest>
{
  static const char* value()
  {
    return DataType< ::tugas_pkg::magnitude >::value();
  }
  static const char* value(const ::tugas_pkg::magnitudeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tugas_pkg::magnitudeResponse> should match
// service_traits::MD5Sum< ::tugas_pkg::magnitude >
template<>
struct MD5Sum< ::tugas_pkg::magnitudeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tugas_pkg::magnitude >::value();
  }
  static const char* value(const ::tugas_pkg::magnitudeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tugas_pkg::magnitudeResponse> should match
// service_traits::DataType< ::tugas_pkg::magnitude >
template<>
struct DataType< ::tugas_pkg::magnitudeResponse>
{
  static const char* value()
  {
    return DataType< ::tugas_pkg::magnitude >::value();
  }
  static const char* value(const ::tugas_pkg::magnitudeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TUGAS_PKG_MESSAGE_MAGNITUDE_H
